//! Cross-language conformance: the Rust `dynamics` port must reproduce the
//! Swift `DialecticalDynamics`, case for case.
//!
//! The fixture is generated by `Sources/DialecticFixture/main.swift` on the
//! `feat/dialectic-conformance-fixture` branch of the NeuralCompose repo, and
//! committed here at `tests/fixtures/dialectic_v1.json`.
//!
//! **Regeneration needs the Mac.** The Linux dev box has the NeuralCompose
//! checkout at `~/src/NeuralCompose` but no Swift toolchain; the Mac has the
//! toolchain but keeps its checkout at `~/Developer/NeuralCompose`, whose main
//! worktree is usually deep in unrelated in-flight work. So regeneration runs
//! in a dedicated worktree, and the command below is the one that was actually
//! used — run it from the root of THIS repo on Linux:
//!
//! ```text
//! ssh mac 'cd ~/Developer/NeuralCompose-dialectic-fixture \
//!          && git pull --ff-only \
//!          && swift build --product dialectic-fixture >/dev/null 2>&1 \
//!          && ./.build/debug/dialectic-fixture 2>/dev/null' \
//!   > crates/neuralcompose-hypnagogic/tests/fixtures/dialectic_v1.json
//!
//! python3 -m json.tool \
//!   < crates/neuralcompose-hypnagogic/tests/fixtures/dialectic_v1.json >/dev/null
//! ```
//!
//! The worktree is created once with
//! `git worktree add ~/Developer/NeuralCompose-dialectic-fixture feat/dialectic-conformance-fixture`
//! from `~/Developer/NeuralCompose`, and any checkout of that branch works —
//! the path is a convenience, not a requirement.
//!
//! Two details that are not incidental: the built binary is invoked directly
//! rather than through `swift run` so no build chatter can reach stdout, and
//! the `json.tool` line catches it if any does. A corrupt fixture would fail
//! conformance for entirely the wrong reason.
//!
//! This is the check that makes "port" a claim rather than a description of
//! intent — the same role `band_power.rs`'s 12-significant-figure assertion
//! against the Python reference plays. `dynamics.rs`'s own unit tests prove it
//! is consistent with itself, which a uniformly mis-transcribed constant would
//! also satisfy.
//!
//! **A missing fixture fails.** It does not skip. A conformance test that
//! quietly passes when its ground truth is absent is worse than no test: it
//! reports green for exactly the state it exists to detect.

use neuralcompose_hypnagogic::dynamics::{
    self, DialecticalCandidate, DialecticalEnergy, DialecticalOutcome, ScoredCandidate, Tuning,
};
use neuralcompose_hypnagogic::embedding::Embedding;
use neuralcompose_hypnagogic::profile::ContextProfile;
use serde::Deserialize;

const FIXTURE_PATH: &str = "tests/fixtures/dialectic_v1.json";

/// Scores, tension, temperature and probabilities are `f32` on both sides;
/// 1e-6 is a transcription check, not a numerics check.
const TOL: f32 = 1e-6;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    schema_id: String,
    model_id: String,
    draws_consumed: Vec<f64>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    name: String,
    profile: String,
    heard: Vec<f32>,
    history_centroid: Option<Vec<f32>>,
    reply_centroid: Option<Vec<f32>>,
    candidates: Vec<CaseCandidate>,
    tension: f32,
    /// True when the harness passed tension to `compete` directly instead of
    /// deriving it from the candidate embeddings. Boundary cases do this so a
    /// comparison operator can be exercised at exact equality, which a cosine
    /// -derived tension cannot reach reliably in `f32`.
    #[serde(default)]
    tension_injected: bool,
    selection_temperature: f32,
    probabilities: Vec<f32>,
    draw: f64,
    margin: f32,
    decisive: bool,
    outcome: String,
    spoken_text: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CaseCandidate {
    role_id: String,
    embedding: Vec<f32>,
    coherence: f32,
    resonance: f32,
    novelty: f32,
    potential: f32,
}

fn load() -> Fixture {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_PATH);
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "conformance fixture missing at {}: {e}\n\n\
             The Rust dynamics port has NOT been checked against the Swift.\n\n\
             Regenerate it from this repo's root. Needs the Mac: the Linux box \
             has no Swift toolchain, and the Mac keeps NeuralCompose at \
             ~/Developer, not ~/src.\n\n  \
             ssh mac 'cd ~/Developer/NeuralCompose-dialectic-fixture\n  \
               git pull --ff-only >/dev/null 2>&1\n  \
               swift build --product dialectic-fixture >/dev/null 2>&1\n  \
               exec ./.build/debug/dialectic-fixture 2>/dev/null' \\\n    \
               > crates/neuralcompose-hypnagogic/{FIXTURE_PATH}\n\n  \
             python3 -m json.tool < crates/neuralcompose-hypnagogic/{FIXTURE_PATH} >/dev/null\n\n\
             Silence EVERY setup step. Chaining with && and leaving git pull loud\n\
             puts \"Already up to date.\" at the head of the fixture — a 20-byte\n\
             prefix that invalidates the JSON while the file still looks the\n\
             right size. The json.tool line is what catches that.\n\n\
             If that worktree is gone, recreate it from ~/Developer/NeuralCompose:\n  \
             git worktree add ~/Developer/NeuralCompose-dialectic-fixture \
             feat/dialectic-conformance-fixture\n",
            path.display()
        )
    });
    serde_json::from_str(&raw).expect("fixture is valid JSON matching this schema")
}

fn close(a: f32, b: f32) -> bool {
    (a - b).abs() <= TOL
}

fn profile_tuning(id: &str) -> Tuning {
    match id {
        "focused" => ContextProfile::Focused.tuning(),
        "reflective" => ContextProfile::Reflective.tuning(),
        "contemplative" => ContextProfile::Contemplative.tuning(),
        other => panic!("fixture names an unknown profile: {other}"),
    }
}

/// The fixture must actually exercise the port. A file with no cases, or one
/// that never reaches silence or a multi-way competition, would pass every
/// assertion below while proving nothing — the always-passing shape.
#[test]
fn the_fixture_covers_the_paths_that_matter() {
    let f = load();
    assert_eq!(
        f.schema_id, "neuralcompose.hypnagogic.dialectic-conformance.v1",
        "fixture schema changed; re-read the harness before trusting it"
    );
    assert!(f.cases.len() >= 20, "fixture is too small to discriminate");
    assert_eq!(
        f.draws_consumed.len(),
        f.cases.len(),
        "every case must record the draw it consumed"
    );

    for p in ["focused", "reflective", "contemplative"] {
        assert!(
            f.cases.iter().any(|c| c.profile == p),
            "no case exercises the {p} profile"
        );
    }
    assert!(
        f.cases.iter().any(|c| c.outcome == "silent"),
        "no case reaches the stalemate/silence gate"
    );
    assert!(
        f.cases.iter().any(|c| c.outcome.starts_with("spoke:")),
        "no case resolves to a spoken basin"
    );
    assert!(
        f.cases.iter().any(|c| c.candidates.len() > 2),
        "no case has more than two candidates; a port hard-coded to two poles \
         would pass everything else"
    );
    assert!(
        f.cases.iter().any(|c| c.candidates.len() == 1),
        "no single-candidate case; the margin edge is untested"
    );
    assert!(
        f.cases.iter().any(|c| c.candidates.is_empty()),
        "no empty-competition case"
    );
    assert!(
        f.cases.iter().any(|c| c.history_centroid.is_none()),
        "no early-turn case; the neutral-0.5 path is untested"
    );
    assert!(
        f.cases.iter().any(|c| c.history_centroid.is_some()),
        "no established-dialogue case"
    );

    // Different draws must actually select different basins somewhere, or the
    // recorded draws are decorative and the whole injected-draw design is unproven.
    for marker in [
        "boundary-tension-exactly-at-bar",
        "boundary-tension-just-under-bar",
        "boundary-draw-exactly-on-cumulative",
    ] {
        assert!(
            f.cases.iter().any(|c| c.name.contains(marker)),
            "fixture is missing the {marker} case; a mutation run showed the \
             derived-tension cases alone cannot discriminate the comparison \
             operators these sit exactly on"
        );
    }
    assert!(
        f.cases.iter().any(|c| c.tension_injected),
        "no case injects tension; the silence-gate boundary is unreachable"
    );

    let bifurcations: Vec<_> = f
        .cases
        .iter()
        .filter(|c| c.name.contains("bifurcation"))
        .collect();
    assert!(
        bifurcations.len() >= 2,
        "no bifurcation sweep in the fixture"
    );
    let distinct: std::collections::HashSet<_> =
        bifurcations.iter().map(|c| c.outcome.as_str()).collect();
    assert!(
        distinct.len() >= 2,
        "every bifurcation draw produced the same outcome ({distinct:?}); the \
         draw sweep is not exercising selection"
    );
}

/// Every intermediate quantity, case by case.
#[test]
fn rust_dynamics_reproduce_the_swift() {
    let f = load();
    let mut failures: Vec<String> = Vec::new();

    for case in &f.cases {
        let tuning = profile_tuning(&case.profile);
        let heard = Embedding::new(case.heard.clone(), &f.model_id);
        let history = case
            .history_centroid
            .as_ref()
            .map(|v| Embedding::new(v.clone(), &f.model_id));
        let reply = case
            .reply_centroid
            .as_ref()
            .map(|v| Embedding::new(v.clone(), &f.model_id));

        let mut scored = Vec::new();
        for fc in &case.candidates {
            let embedding = Embedding::new(fc.embedding.clone(), &f.model_id);
            let energy =
                match dynamics::energy(&embedding, &heard, history.as_ref(), reply.as_ref()) {
                    Some(e) => e,
                    None => {
                        failures.push(format!(
                            "{}: candidate {} scored as incomparable",
                            case.name, fc.role_id
                        ));
                        continue;
                    }
                };
            let potential = energy.potential(&tuning.weights);

            for (axis, got, want) in [
                ("coherence", energy.coherence, fc.coherence),
                ("resonance", energy.resonance, fc.resonance),
                ("novelty", energy.novelty, fc.novelty),
                ("potential", potential, fc.potential),
            ] {
                if !close(got, want) {
                    failures.push(format!(
                        "{}: candidate {} {axis}: rust {got} vs swift {want}",
                        case.name, fc.role_id
                    ));
                }
            }

            scored.push(ScoredCandidate {
                candidate: DialecticalCandidate {
                    text: format!("candidate-{}", fc.role_id),
                    embedding,
                    role_id: fc.role_id.clone(),
                },
                energy: DialecticalEnergy {
                    coherence: fc.coherence,
                    resonance: fc.resonance,
                    novelty: fc.novelty,
                },
                potential: fc.potential,
                role_fulfillment: 0.0,
            });
        }

        // Tension, over the same candidate embeddings the Swift used.
        let embeddings: Vec<Embedding> = case
            .candidates
            .iter()
            .map(|c| Embedding::new(c.embedding.clone(), &f.model_id))
            .collect();
        if !case.tension_injected {
            match dynamics::tension(&embeddings) {
                Some(t) if close(t, case.tension) => {}
                Some(t) => failures.push(format!(
                    "{}: tension: rust {t} vs swift {}",
                    case.name, case.tension
                )),
                None => failures.push(format!("{}: tension came back incomparable", case.name)),
            }
        }

        let tau = dynamics::selection_temperature(case.tension, &tuning);
        if !close(tau, case.selection_temperature) {
            failures.push(format!(
                "{}: selection temperature: rust {tau} vs swift {}",
                case.name, case.selection_temperature
            ));
        }

        let potentials: Vec<f32> = case.candidates.iter().map(|c| c.potential).collect();
        let probs = dynamics::probabilities(&potentials, case.selection_temperature);
        if probs.len() != case.probabilities.len() {
            failures.push(format!(
                "{}: probability count: rust {} vs swift {}",
                case.name,
                probs.len(),
                case.probabilities.len()
            ));
        } else {
            for (i, (got, want)) in probs.iter().zip(case.probabilities.iter()).enumerate() {
                if !close(*got, *want) {
                    failures.push(format!(
                        "{}: probability[{i}]: rust {got} vs swift {want}",
                        case.name
                    ));
                }
            }
        }

        // Resolution, with the RECORDED draw replayed — not a seed.
        let r = dynamics::compete(&scored, case.tension, case.draw, &tuning, None, false);
        if !close(r.margin, case.margin) {
            failures.push(format!(
                "{}: margin: rust {} vs swift {}",
                case.name, r.margin, case.margin
            ));
        }
        if r.decisive != case.decisive {
            failures.push(format!(
                "{}: decisive: rust {} vs swift {}",
                case.name, r.decisive, case.decisive
            ));
        }
        let (outcome, spoken) = match &r.outcome {
            DialecticalOutcome::Spoke(c) => (format!("spoke:{}", c.role_id), c.text.clone()),
            DialecticalOutcome::Synthesized(c) => {
                (format!("synthesized:{}", c.role_id), c.text.clone())
            }
            DialecticalOutcome::Silent => ("silent".to_string(), String::new()),
        };
        if outcome != case.outcome {
            // The diagnostic is only meaningful because the draw is injected:
            // with a seed, this would fire on every correct port.
            let scores_agree = close(r.margin, case.margin);
            failures.push(format!(
                "{}: outcome: rust {outcome} vs swift {} (draw {}, scores {}) — \
                 scores agreeing here points at the softmax/temperature path, \
                 not at the draw",
                case.name,
                case.outcome,
                case.draw,
                if scores_agree { "agree" } else { "differ" }
            ));
        } else if outcome.starts_with("spoke:") && !case.spoken_text.is_empty() {
            let want_role = case.outcome.trim_start_matches("spoke:");
            assert!(
                spoken.contains(want_role),
                "{}: selected candidate does not carry its role provenance",
                case.name
            );
        }
    }

    assert!(
        failures.is_empty(),
        "the Rust port diverges from the Swift in {} place(s):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}
