// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(neuralcompose_mobile_coreFFI)
import neuralcompose_mobile_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_neuralcompose_mobile_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_neuralcompose_mobile_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNeuralcomposeMobileCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol StreamMonitorProtocol: AnyObject, Sendable {
    
    /**
     * Shell hands over one raw WS text frame. Returns the number of samples
     * accepted. `last_received_at_ms` advances ONLY when accepted > 0 —
     * this pins the Gate 4 no-op-flush bug: retained data and empty or
     * invalid frames must never refresh sample age.
     */
    func onFrame(text: String, nowMs: UInt64)  -> UInt32
    
    /**
     * Shell reports socket lifecycle. `Opened` resets the attempt counter;
     * `Closed`/`Errored` count one failed attempt each and never schedule
     * anything themselves — the shell asks `reconnect_decision()` and owns
     * the timer.
     */
    func onSocketEvent(event: SocketEvent, nowMs: UInt64) 
    
    /**
     * Read-only phase derivation. MUST NOT mutate receive state.
     */
    func phase(nowMs: UInt64)  -> StreamPhase
    
    func presentation(nowMs: UInt64)  -> Presentation
    
    /**
     * Pure decision from the current failed-attempt count. When it returns
     * `GiveUp` the monitor latches `Error` (matching the Expo client, which
     * reports `error` after exhausting its 3 attempts).
     */
    func reconnectDecision()  -> ReconnectDecision
    
    /**
     * New subscription lifecycle (mirrors the Expo hook's remount reset).
     */
    func reset() 
    
    func snapshot()  -> ChannelSnapshot
    
}
open class StreamMonitor: StreamMonitorProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_neuralcompose_mobile_core_fn_clone_streammonitor(self.handle, $0) }
    }
public convenience init(config: MonitorConfig) {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_constructor_streammonitor_new(
        FfiConverterTypeMonitorConfig_lower(config),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_neuralcompose_mobile_core_fn_free_streammonitor(handle, $0) }
    }

    
public static func withDefaults() -> StreamMonitor  {
    return try!  FfiConverterTypeStreamMonitor_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_constructor_streammonitor_with_defaults(uniffiCallStatus
    )
})
}
    

    
    /**
     * Shell hands over one raw WS text frame. Returns the number of samples
     * accepted. `last_received_at_ms` advances ONLY when accepted > 0 —
     * this pins the Gate 4 no-op-flush bug: retained data and empty or
     * invalid frames must never refresh sample age.
     */
open func onFrame(text: String, nowMs: UInt64) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_on_frame(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterUInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
    /**
     * Shell reports socket lifecycle. `Opened` resets the attempt counter;
     * `Closed`/`Errored` count one failed attempt each and never schedule
     * anything themselves — the shell asks `reconnect_decision()` and owns
     * the timer.
     */
open func onSocketEvent(event: SocketEvent, nowMs: UInt64)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_on_socket_event(
            self.uniffiCloneHandle(),
        FfiConverterTypeSocketEvent_lower(event),
        FfiConverterUInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Read-only phase derivation. MUST NOT mutate receive state.
     */
open func phase(nowMs: UInt64) -> StreamPhase  {
    return try!  FfiConverterTypeStreamPhase_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_phase(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
open func presentation(nowMs: UInt64) -> Presentation  {
    return try!  FfiConverterTypePresentation_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_presentation(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
    /**
     * Pure decision from the current failed-attempt count. When it returns
     * `GiveUp` the monitor latches `Error` (matching the Expo client, which
     * reports `error` after exhausting its 3 attempts).
     */
open func reconnectDecision() -> ReconnectDecision  {
    return try!  FfiConverterTypeReconnectDecision_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_reconnect_decision(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * New subscription lifecycle (mirrors the Expo hook's remount reset).
     */
open func reset()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_reset(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
open func snapshot() -> ChannelSnapshot  {
    return try!  FfiConverterTypeChannelSnapshot_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_method_streammonitor_snapshot(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamMonitor: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = StreamMonitor

    public static func lift(_ handle: UInt64) throws -> StreamMonitor {
        return StreamMonitor(unsafeFromHandle: handle)
    }

    public static func lower(_ value: StreamMonitor) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamMonitor {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: StreamMonitor, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamMonitor_lift(_ handle: UInt64) throws -> StreamMonitor {
    return try FfiConverterTypeStreamMonitor.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamMonitor_lower(_ value: StreamMonitor) -> UInt64 {
    return FfiConverterTypeStreamMonitor.lower(value)
}




public struct ChannelSnapshot: Equatable, Hashable {
    /**
     * 4 vecs in fixed TP9, AF7, AF8, TP10 order; newest `keep` samples.
     */
    public var channels: [[Double]]
    /**
     * Index of the newest sample within the snapshot window; -1 when empty
     * (mirrors the Expo `EEGBuffer.latest`).
     */
    public var latestIndex: Int64
    /**
     * Total samples accepted since the last `reset()`.
     */
    public var received: UInt64
    /**
     * Monotonic ms of the newest ACCEPTED sample; `None` before the first.
     */
    public var lastReceivedAtMs: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 4 vecs in fixed TP9, AF7, AF8, TP10 order; newest `keep` samples.
         */channels: [[Double]], 
        /**
         * Index of the newest sample within the snapshot window; -1 when empty
         * (mirrors the Expo `EEGBuffer.latest`).
         */latestIndex: Int64, 
        /**
         * Total samples accepted since the last `reset()`.
         */received: UInt64, 
        /**
         * Monotonic ms of the newest ACCEPTED sample; `None` before the first.
         */lastReceivedAtMs: UInt64?) {
        self.channels = channels
        self.latestIndex = latestIndex
        self.received = received
        self.lastReceivedAtMs = lastReceivedAtMs
    }

    

    
}

#if compiler(>=6)
extension ChannelSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChannelSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChannelSnapshot {
        return
            try ChannelSnapshot(
                channels: FfiConverterSequenceSequenceDouble.read(from: &buf), 
                latestIndex: FfiConverterInt64.read(from: &buf), 
                received: FfiConverterUInt64.read(from: &buf), 
                lastReceivedAtMs: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ChannelSnapshot, into buf: inout [UInt8]) {
        FfiConverterSequenceSequenceDouble.write(value.channels, into: &buf)
        FfiConverterInt64.write(value.latestIndex, into: &buf)
        FfiConverterUInt64.write(value.received, into: &buf)
        FfiConverterOptionUInt64.write(value.lastReceivedAtMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChannelSnapshot_lift(_ buf: RustBuffer) throws -> ChannelSnapshot {
    return try FfiConverterTypeChannelSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChannelSnapshot_lower(_ value: ChannelSnapshot) -> RustBuffer {
    return FfiConverterTypeChannelSnapshot.lower(value)
}


public struct MonitorConfig: Equatable, Hashable {
    public var keepSamples: UInt32
    public var staleAfterMs: UInt64
    public var maxReconnectAttempts: UInt32
    public var backoffBaseMs: UInt64
    public var backoffCapMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(keepSamples: UInt32, staleAfterMs: UInt64, maxReconnectAttempts: UInt32, backoffBaseMs: UInt64, backoffCapMs: UInt64) {
        self.keepSamples = keepSamples
        self.staleAfterMs = staleAfterMs
        self.maxReconnectAttempts = maxReconnectAttempts
        self.backoffBaseMs = backoffBaseMs
        self.backoffCapMs = backoffCapMs
    }

    

    
}

#if compiler(>=6)
extension MonitorConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMonitorConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MonitorConfig {
        return
            try MonitorConfig(
                keepSamples: FfiConverterUInt32.read(from: &buf), 
                staleAfterMs: FfiConverterUInt64.read(from: &buf), 
                maxReconnectAttempts: FfiConverterUInt32.read(from: &buf), 
                backoffBaseMs: FfiConverterUInt64.read(from: &buf), 
                backoffCapMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MonitorConfig, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.keepSamples, into: &buf)
        FfiConverterUInt64.write(value.staleAfterMs, into: &buf)
        FfiConverterUInt32.write(value.maxReconnectAttempts, into: &buf)
        FfiConverterUInt64.write(value.backoffBaseMs, into: &buf)
        FfiConverterUInt64.write(value.backoffCapMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMonitorConfig_lift(_ buf: RustBuffer) throws -> MonitorConfig {
    return try FfiConverterTypeMonitorConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMonitorConfig_lower(_ value: MonitorConfig) -> RustBuffer {
    return FfiConverterTypeMonitorConfig.lower(value)
}


public struct Presentation: Equatable, Hashable {
    public var phase: StreamPhase
    public var tone: StreamTone
    /**
     * `floor(age_ms / 1000)` when the phase is `Stale`, else `None`.
     */
    public var ageS: UInt64?
    /**
     * "Stream silent — no samples for Ns (socket still open)"
     */
    public var showSilentBanner: Bool
    /**
     * "Stream disconnected — showing last cached data"
     */
    public var showDisconnectedBanner: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(phase: StreamPhase, tone: StreamTone, 
        /**
         * `floor(age_ms / 1000)` when the phase is `Stale`, else `None`.
         */ageS: UInt64?, 
        /**
         * "Stream silent — no samples for Ns (socket still open)"
         */showSilentBanner: Bool, 
        /**
         * "Stream disconnected — showing last cached data"
         */showDisconnectedBanner: Bool) {
        self.phase = phase
        self.tone = tone
        self.ageS = ageS
        self.showSilentBanner = showSilentBanner
        self.showDisconnectedBanner = showDisconnectedBanner
    }

    

    
}

#if compiler(>=6)
extension Presentation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePresentation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Presentation {
        return
            try Presentation(
                phase: FfiConverterTypeStreamPhase.read(from: &buf), 
                tone: FfiConverterTypeStreamTone.read(from: &buf), 
                ageS: FfiConverterOptionUInt64.read(from: &buf), 
                showSilentBanner: FfiConverterBool.read(from: &buf), 
                showDisconnectedBanner: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Presentation, into buf: inout [UInt8]) {
        FfiConverterTypeStreamPhase.write(value.phase, into: &buf)
        FfiConverterTypeStreamTone.write(value.tone, into: &buf)
        FfiConverterOptionUInt64.write(value.ageS, into: &buf)
        FfiConverterBool.write(value.showSilentBanner, into: &buf)
        FfiConverterBool.write(value.showDisconnectedBanner, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePresentation_lift(_ buf: RustBuffer) throws -> Presentation {
    return try FfiConverterTypePresentation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePresentation_lower(_ value: Presentation) -> RustBuffer {
    return FfiConverterTypePresentation.lower(value)
}


public struct ResolvedClientConfig: Equatable, Hashable {
    public var mode: ClientMode
    public var serverUrl: String
    public var eegWsUrl: String
    /**
     * Non-empty when live mode is selected but endpoints are unusable.
     */
    public var configError: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(mode: ClientMode, serverUrl: String, eegWsUrl: String, 
        /**
         * Non-empty when live mode is selected but endpoints are unusable.
         */configError: String?) {
        self.mode = mode
        self.serverUrl = serverUrl
        self.eegWsUrl = eegWsUrl
        self.configError = configError
    }

    

    
}

#if compiler(>=6)
extension ResolvedClientConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeResolvedClientConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResolvedClientConfig {
        return
            try ResolvedClientConfig(
                mode: FfiConverterTypeClientMode.read(from: &buf), 
                serverUrl: FfiConverterString.read(from: &buf), 
                eegWsUrl: FfiConverterString.read(from: &buf), 
                configError: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ResolvedClientConfig, into buf: inout [UInt8]) {
        FfiConverterTypeClientMode.write(value.mode, into: &buf)
        FfiConverterString.write(value.serverUrl, into: &buf)
        FfiConverterString.write(value.eegWsUrl, into: &buf)
        FfiConverterOptionString.write(value.configError, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResolvedClientConfig_lift(_ buf: RustBuffer) throws -> ResolvedClientConfig {
    return try FfiConverterTypeResolvedClientConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResolvedClientConfig_lower(_ value: ResolvedClientConfig) -> RustBuffer {
    return FfiConverterTypeResolvedClientConfig.lower(value)
}



public enum ClientMode: Equatable, Hashable {
    
    case mock
    case live





}

#if compiler(>=6)
extension ClientMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientMode: FfiConverterRustBuffer {
    typealias SwiftType = ClientMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .mock
        
        case 2: return .live
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ClientMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .mock:
            writeInt(&buf, Int32(1))
        
        
        case .live:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientMode_lift(_ buf: RustBuffer) throws -> ClientMode {
    return try FfiConverterTypeClientMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientMode_lower(_ value: ClientMode) -> RustBuffer {
    return FfiConverterTypeClientMode.lower(value)
}




public enum ReconnectDecision: Equatable, Hashable {
    
    case retryAfterMs(delayMs: UInt64
    )
    case giveUp





}

#if compiler(>=6)
extension ReconnectDecision: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReconnectDecision: FfiConverterRustBuffer {
    typealias SwiftType = ReconnectDecision

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReconnectDecision {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .retryAfterMs(delayMs: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 2: return .giveUp
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ReconnectDecision, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .retryAfterMs(delayMs):
            writeInt(&buf, Int32(1))
            FfiConverterUInt64.write(delayMs, into: &buf)
            
        
        case .giveUp:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReconnectDecision_lift(_ buf: RustBuffer) throws -> ReconnectDecision {
    return try FfiConverterTypeReconnectDecision.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReconnectDecision_lower(_ value: ReconnectDecision) -> RustBuffer {
    return FfiConverterTypeReconnectDecision.lower(value)
}




public enum SocketEvent: Equatable, Hashable {
    
    case connecting
    case opened
    case closed
    case errored





}

#if compiler(>=6)
extension SocketEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSocketEvent: FfiConverterRustBuffer {
    typealias SwiftType = SocketEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SocketEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connecting
        
        case 2: return .opened
        
        case 3: return .closed
        
        case 4: return .errored
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SocketEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connecting:
            writeInt(&buf, Int32(1))
        
        
        case .opened:
            writeInt(&buf, Int32(2))
        
        
        case .closed:
            writeInt(&buf, Int32(3))
        
        
        case .errored:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSocketEvent_lift(_ buf: RustBuffer) throws -> SocketEvent {
    return try FfiConverterTypeSocketEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSocketEvent_lower(_ value: SocketEvent) -> RustBuffer {
    return FfiConverterTypeSocketEvent.lower(value)
}



/**
 * The operator-specified stream phase.
 */

public enum StreamPhase: Equatable, Hashable {
    
    case connecting
    case openNoData
    case live
    case stale(ageMs: UInt64
    )
    case closed
    case error





}

#if compiler(>=6)
extension StreamPhase: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamPhase: FfiConverterRustBuffer {
    typealias SwiftType = StreamPhase

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamPhase {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connecting
        
        case 2: return .openNoData
        
        case 3: return .live
        
        case 4: return .stale(ageMs: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 5: return .closed
        
        case 6: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StreamPhase, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connecting:
            writeInt(&buf, Int32(1))
        
        
        case .openNoData:
            writeInt(&buf, Int32(2))
        
        
        case .live:
            writeInt(&buf, Int32(3))
        
        
        case let .stale(ageMs):
            writeInt(&buf, Int32(4))
            FfiConverterUInt64.write(ageMs, into: &buf)
            
        
        case .closed:
            writeInt(&buf, Int32(5))
        
        
        case .error:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamPhase_lift(_ buf: RustBuffer) throws -> StreamPhase {
    return try FfiConverterTypeStreamPhase.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamPhase_lower(_ value: StreamPhase) -> RustBuffer {
    return FfiConverterTypeStreamPhase.lower(value)
}




public enum StreamTone: Equatable, Hashable {
    
    case ok
    case stale
    case connecting
    case down





}

#if compiler(>=6)
extension StreamTone: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamTone: FfiConverterRustBuffer {
    typealias SwiftType = StreamTone

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamTone {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ok
        
        case 2: return .stale
        
        case 3: return .connecting
        
        case 4: return .down
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StreamTone, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ok:
            writeInt(&buf, Int32(1))
        
        
        case .stale:
            writeInt(&buf, Int32(2))
        
        
        case .connecting:
            writeInt(&buf, Int32(3))
        
        
        case .down:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamTone_lift(_ buf: RustBuffer) throws -> StreamTone {
    return try FfiConverterTypeStreamTone.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamTone_lower(_ value: StreamTone) -> RustBuffer {
    return FfiConverterTypeStreamTone.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]

    public static func write(_ value: [Double], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterDouble.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Double] {
        let len: Int32 = try readInt(&buf)
        var seq = [Double]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterDouble.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [[Double]]

    public static func write(_ value: [[Double]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceDouble.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[Double]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[Double]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceDouble.read(from: &buf))
        }
        return seq
    }
}
/**
 * Derive the ws(s):// stream URL from the HTTP server URL when not given.
 */
public func deriveWsUrl(serverUrl: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_func_derive_ws_url(
        FfiConverterString.lower(serverUrl),uniffiCallStatus
    )
})
}
/**
 * "false"/"0"/"no" (any case) select live mode; everything else stays mock.
 */
public func parseUseMock(raw: String?) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_func_parse_use_mock(
        FfiConverterOptionString.lower(raw),uniffiCallStatus
    )
})
}
public func resolveClientMode(useMockRaw: String?, serverRaw: String?, wsRaw: String?) -> ResolvedClientConfig  {
    return try!  FfiConverterTypeResolvedClientConfig_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_func_resolve_client_mode(
        FfiConverterOptionString.lower(useMockRaw),
        FfiConverterOptionString.lower(serverRaw),
        FfiConverterOptionString.lower(wsRaw),uniffiCallStatus
    )
})
}
/**
 * English banner — must reproduce the Expo Jest oracle strings exactly.
 */
public func formatBannerEn(p: Presentation) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_func_format_banner_en(
        FfiConverterTypePresentation_lower(p),uniffiCallStatus
    )
})
}
/**
 * English pill label — must reproduce the Expo Jest oracle strings exactly.
 */
public func formatLabelEn(p: Presentation) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_neuralcompose_mobile_core_fn_func_format_label_en(
        FfiConverterTypePresentation_lower(p),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_neuralcompose_mobile_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_func_derive_ws_url() != 13734) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_func_parse_use_mock() != 32798) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_func_resolve_client_mode() != 9781) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_func_format_banner_en() != 12060) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_func_format_label_en() != 32187) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_on_frame() != 9867) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_on_socket_event() != 31328) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_phase() != 30052) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_presentation() != 23850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_reconnect_decision() != 51196) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_reset() != 55966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_method_streammonitor_snapshot() != 32385) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_constructor_streammonitor_new() != 40578) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neuralcompose_mobile_core_checksum_constructor_streammonitor_with_defaults() != 29225) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNeuralcomposeMobileCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all